In [4]:
import pandas as pd
import glob
import os
import re
from tqdm import tqdm
from pathlib import Path

In [5]:
# Descobre onde o notebook está e sobe uma pasta para achar a raiz do projeto
base_dir = Path().resolve().parent 
data_dir = base_dir / "data"

# 1 ABERTURA DOS DADOS

In [6]:
caminho = fr'{data_dir}\ac_por_pessoa\*.csv'
arquivos = glob.glob(caminho)

print(arquivos)
print(len(arquivos), "arquivos encontrados")

['C:\\Users\\Elaine\\Desktop\\TCC_acidentes\\data\\ac_por_pessoa\\acidentes2023_todas_causas_tipos.csv', 'C:\\Users\\Elaine\\Desktop\\TCC_acidentes\\data\\ac_por_pessoa\\acidentes2024_todas_causas_tipos.csv', 'C:\\Users\\Elaine\\Desktop\\TCC_acidentes\\data\\ac_por_pessoa\\acidentes2025_todas_causas_tipos.csv']
3 arquivos encontrados

## 1.1 PRF

In [7]:
# Caminho onde estão os arquivos de acidentes
path_acidentes = fr'{data_dir}\ac_por_pessoa\*.csv'

lista_acidentes = []

for arquivo in tqdm(glob.glob(path_acidentes)):
    
    # Lê o CSV
    df = pd.read_csv(arquivo, encoding="ISO-8859-1", sep=";")
    
    # Filtrar colunas que você precisa
    df = df[['uf', 'br', 'km', 'municipio', 'dia_semana', 'fase_dia', 'sentido_via',
             'condicao_metereologica', 'tipo_pista', 'tracado_via', 'uso_solo',
             'tipo_veiculo', 'data_inversa', 'estado_fisico', "latitude", "longitude"]]
    
    # Converte data
    df["data_inversa"] = pd.to_datetime(df["data_inversa"], errors="coerce")
    
    # Extrair ano
    df["ano"] = df["data_inversa"].dt.year
    
    lista_acidentes.append(df)

# Concatena tudo em um dataframe só
prf = pd.concat(lista_acidentes, ignore_index=True)
prf.info()
prf.head()

100%|██████████| 3/3 [00:38<00:00, 12.78s/it]

<class 'pandas.DataFrame'>
RangeIndex: 1758277 entries, 0 to 1758276
Data columns (total 17 columns):
 #   Column                  Dtype
---  ------                  -----
 0   uf                      str
 1   br                      float64
 2   km                      str
 3   municipio               str
 4   dia_semana              str
 5   fase_dia                str
 6   sentido_via             str
 7   condicao_metereologica  str
 8   tipo_pista              str
 9   tracado_via             str
 10  uso_solo                str
 11  tipo_veiculo            str
 12  data_inversa            datetime64[us]
 13  estado_fisico           str
 14  latitude                object
 15  longitude               object
 16  ano                     int32
dtypes: datetime64[us](1), float64(1), int32(1), object(2), str(12)
memory usage: 376.9+ MB

,uf,br,km,municipio,dia_semana,fase_dia,sentido_via,condicao_metereologica,tipo_pista,tracado_via,uso_solo,tipo_veiculo,data_inversa,estado_fisico,latitude,longitude,ano
0,MG,116.0,587,MANHUACU,domingo,Plena Noite,Crescente,Nublado,Simples,Reta,Sim,Motocicleta,2023-01-01,Lesões Leves,"-20,24173903","-42,15868042",2023
1,MG,116.0,587,MANHUACU,domingo,Plena Noite,Crescente,Nublado,Simples,Reta,Sim,Motocicleta,2023-01-01,Lesões Leves,"-20,24173903","-42,15868042",2023
2,MG,116.0,587,MANHUACU,domingo,Plena Noite,Crescente,Nublado,Simples,Reta,Sim,Motocicleta,2023-01-01,Lesões Leves,"-20,24173903","-42,15868042",2023
3,MG,116.0,587,MANHUACU,domingo,Plena Noite,Crescente,Nublado,Simples,Reta,Sim,Motocicleta,2023-01-01,Lesões Leves,"-20,24173903","-42,15868042",2023
4,MG,381.0,"686,5",LAVRAS,domingo,Pleno dia,Decrescente,Garoa/Chuvisco,Dupla,Curva,Não,Automóvel,2023-01-01,Lesões Leves,"-21,17928973","-45,12256622",2023

## 1.2 Frota

In [8]:
path_frota = fr'{data_dir}\frota\*.*'

lista_frotas = []

def extrair_ano_primeira_linha(arquivo):
    df_tmp = pd.read_excel(arquivo, header=None, nrows=1, dtype=str)
    linha = str(df_tmp.iloc[0, 0])

    ano = re.findall(r'(\d{4})', linha)
    if ano:
        return int(ano[-1])
    else:
        raise ValueError(f"Não foi possível extrair o ano do arquivo: {arquivo}")

def encontrar_header(arquivo):
    """
    Procura em qual linha está o cabeçalho (onde aparece 'UF')
    """
    df_tmp = pd.read_excel(arquivo, header=None, nrows=10)

    for i, row in df_tmp.iterrows():
        valores = row.astype(str).str.upper().tolist()
        if "UF" in valores:
            return i  # linha onde está o header

    raise ValueError(f"Cabeçalho não encontrado no arquivo: {arquivo}")


# leitura das tabelas de frota
arquivos = glob.glob(fr'{data_dir}\frota\*.xls') + \
           glob.glob(fr'{data_dir}\frota\*.xlsx')

for arquivo in tqdm(arquivos):

    # ignora arquivos que não são por município
    if "munic" not in arquivo.lower():
        print(f"Ignorado: {arquivo}")
        continue

    ano = extrair_ano_primeira_linha(arquivo)

    header_row = encontrar_header(arquivo)

    df = pd.read_excel(arquivo, skiprows=header_row)

    df.columns = df.columns.str.upper().str.strip()

    df = pd.read_excel(arquivo, skiprows=header_row)

    df.columns = df.columns.str.upper().str.strip()

    df = df.rename(columns={
        "UF": "uf",
        "MUNICIPIO": "municipio",
        "MUNICÍPIO": "municipio",
        "TOTAL": "frota"
    })

    # LIMPEZA 
    df = df[~df["uf"].astype(str).str.upper().str.strip().eq("UF")]

    df["frota"] = pd.to_numeric(df["frota"], errors="coerce")
    df = df.dropna(subset=["frota"])

    df["ano"] = ano

    # garante que só pega colunas existentes
    colunas = ["uf", "municipio", "frota", "ano"]
    df = df[[c for c in colunas if c in df.columns]]

    lista_frotas.append(df)

# concatena tudo
frota = pd.concat(lista_frotas, ignore_index=True)

frota.head()

 33%|███▎      | 1/3 [00:05<00:10,  5.14s/it]c:\Users\Elaine\Desktop\TCC_acidentes\venv\Lib\site-packages\openpyxl\worksheet\header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
c:\Users\Elaine\Desktop\TCC_acidentes\venv\Lib\site-packages\openpyxl\worksheet\header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
 67%|██████▋   | 2/3 [00:15<00:08,  8.49s/it]c:\Users\Elaine\Desktop\TCC_acidentes\venv\Lib\site-packages\openpyxl\worksheet\header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
c:\Users\Elaine\Desktop\TCC_acidentes\venv\Lib\site-packages\openpyxl\worksheet\header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
100%|██████████| 3/3 [00:21<00:00,  7.01s/it]

   uf     municipio  frota   ano
0  AC    ACRELANDIA   7898  2023
1  AC  ASSIS BRASIL   2272  2023
2  AC     BRASILEIA  13040  2023
3  AC        BUJARI   2912  2023
4  AC      CAPIXABA   2935  2023

In [9]:
frota[frota["ano"] == 2023]

      uf       municipio  frota   ano
0     AC      ACRELANDIA   7898  2023
1     AC    ASSIS BRASIL   2272  2023
2     AC       BRASILEIA  13040  2023
3     AC          BUJARI   2912  2023
4     AC        CAPIXABA   2935  2023
...   ..             ...    ...   ...
5566  TO  TOCANTINOPOLIS  21126  2023
5567  TO        TUPIRAMA    654  2023
5568  TO      TUPIRATINS    504  2023
5569  TO    WANDERLANDIA   2778  2023
5570  TO         XAMBIOA   5733  2023

[5571 rows x 4 columns]

# 2 ACIDENTES E FROTA

In [10]:
ac_frota = prf.merge(
    frota,
    on=["municipio", "uf", "ano"],
    how="left"
)

ac_frota['gravidade'] = ac_frota['estado_fisico'].apply(
    lambda x: 1 if x in ['Lesões Graves', 'Óbito'] else 0
)

ac_frota['km'] = ac_frota['km'].str.replace(",", ".").astype(float).round(0) #! arredondei os kms

del ac_frota['estado_fisico'], ac_frota['data_inversa'], ac_frota['municipio']

print(ac_frota['gravidade'].value_counts(normalize=True))
ac_frota.info()
ac_frota.head()

gravidade
0    0.837373
1    0.162627
Name: proportion, dtype: float64
<class 'pandas.DataFrame'>
RangeIndex: 1758277 entries, 0 to 1758276
Data columns (total 16 columns):
 #   Column                  Dtype
---  ------                  -----
 0   uf                      str
 1   br                      float64
 2   km                      float64
 3   dia_semana              str
 4   fase_dia                str
 5   sentido_via             str
 6   condicao_metereologica  str
 7   tipo_pista              str
 8   tracado_via             str
 9   uso_solo                str
 10  tipo_veiculo            str
 11  latitude                object
 12  longitude               object
 13  ano                     int32
 14  frota                   float64
 15  gravidade               int64
dtypes: float64(3), int32(1), int64(1), object(2), str(9)
memory usage: 324.8+ MB

,uf,br,km,dia_semana,fase_dia,sentido_via,condicao_metereologica,tipo_pista,tracado_via,uso_solo,tipo_veiculo,latitude,longitude,ano,frota,gravidade
0,MG,116.0,587.0,domingo,Plena Noite,Crescente,Nublado,Simples,Reta,Sim,Motocicleta,"-20,24173903","-42,15868042",2023,50184.0,0
1,MG,116.0,587.0,domingo,Plena Noite,Crescente,Nublado,Simples,Reta,Sim,Motocicleta,"-20,24173903","-42,15868042",2023,50184.0,0
2,MG,116.0,587.0,domingo,Plena Noite,Crescente,Nublado,Simples,Reta,Sim,Motocicleta,"-20,24173903","-42,15868042",2023,50184.0,0
3,MG,116.0,587.0,domingo,Plena Noite,Crescente,Nublado,Simples,Reta,Sim,Motocicleta,"-20,24173903","-42,15868042",2023,50184.0,0
4,MG,381.0,686.0,domingo,Pleno dia,Decrescente,Garoa/Chuvisco,Dupla,Curva,Não,Automóvel,"-21,17928973","-45,12256622",2023,72927.0,0

In [11]:
ac_frota

,uf,br,km,dia_semana,fase_dia,sentido_via,condicao_metereologica,tipo_pista,tracado_via,uso_solo,tipo_veiculo,latitude,longitude,ano,frota,gravidade
0,MG,116.0,587.0,domingo,Plena Noite,Crescente,Nublado,Simples,Reta,Sim,Motocicleta,"-20,24173903","-42,15868042",2023,50184.0,0
1,MG,116.0,587.0,domingo,Plena Noite,Crescente,Nublado,Simples,Reta,Sim,Motocicleta,"-20,24173903","-42,15868042",2023,50184.0,0
2,MG,116.0,587.0,domingo,Plena Noite,Crescente,Nublado,Simples,Reta,Sim,Motocicleta,"-20,24173903","-42,15868042",2023,50184.0,0
3,MG,116.0,587.0,domingo,Plena Noite,Crescente,Nublado,Simples,Reta,Sim,Motocicleta,"-20,24173903","-42,15868042",2023,50184.0,0
4,MG,381.0,686.0,domingo,Pleno dia,Decrescente,Garoa/Chuvisco,Dupla,Curva,Não,Automóvel,"-21,17928973","-45,12256622",2023,72927.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1758272,PR,376.0,315.0,segunda-feira,Pleno dia,Crescente,Nublado,Simples,Curva,Não,Caminhão-trator,"-24,01214","-51,09233",2025,14856.0,0
1758273,SC,101.0,130.0,segunda-feira,Pleno dia,Crescente,Sol,Dupla,Reta,Sim,Automóvel,"-26,99305955","-48,6609548",2025,85991.0,0
1758274,SC,101.0,130.0,segunda-feira,Pleno dia,Crescente,Sol,Dupla,Reta,Sim,Caminhonete,"-26,99305955","-48,6609548",2025,85991.0,0
1758275,MG,381.0,218.0,domingo,Plena Noite,Decrescente,Nublado,Simples,Reta;Interseção de Vias,Não,Automóvel,"-19,298811","-42,371921",2025,12658.0,1
1758276,MG,381.0,218.0,domingo,Plena Noite,Decrescente,Nublado,Simples,Reta;Interseção de Vias,Não,Caminhonete,"-19,298811","-42,371921",2025,12658.0,0

In [12]:
amostra = ac_frota.sample(frac=0.10, random_state=42)

In [13]:
amostra

,uf,br,km,dia_semana,fase_dia,sentido_via,condicao_metereologica,tipo_pista,tracado_via,uso_solo,tipo_veiculo,latitude,longitude,ano,frota,gravidade
154449,RO,364.0,238.0,quinta-feira,Pleno dia,Crescente,Sol,Simples,Reta,Sim,Motocicleta,"-11,438347","-61,455257",2023,81535.0,0
443245,BA,324.0,519.0,sexta-feira,Anoitecer,Decrescente,Céu Claro,Dupla,Reta,Sim,Automóvel,"-12,27956","-38,92571",2023,342906.0,0
1743938,BA,101.0,810.0,quinta-feira,Plena Noite,Crescente,Céu Claro,Simples,Curva,Sim,Automóvel,"-17,037757","-39,546428",2025,30777.0,0
1432426,MT,70.0,530.0,sexta-feira,Amanhecer,Crescente,Nevoeiro/Neblina,Simples,Reta,Não,Motocicleta,"-15,66037","-56,220718",2025,227022.0,1
652908,SP,116.0,229.0,sexta-feira,Pleno dia,Crescente,Garoa/Chuvisco,Múltipla,Reta,Sim,Caminhonete,-23.512919,-46.576047,2024,9748457.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
614521,GO,452.0,168.0,segunda-feira,Pleno dia,Crescente,Céu Claro,Simples,Reta;Aclive,Não,Automóvel,-18.331283,-49.451488,2024,100767.0,1
1105647,MS,163.0,251.0,quarta-feira,Plena Noite,Decrescente,Céu Claro,Simples,Interseção de Vias;Reta,Sim,Micro-ônibus,-22.296887,-54.82117,2024,193173.0,0
180206,MA,135.0,23.0,domingo,Pleno dia,Decrescente,Céu Claro,Dupla,Reta,Sim,Automóvel,"-2,53073","-44,3068",2023,469262.0,0
1220102,RS,290.0,481.0,sábado,Pleno dia,Crescente,Céu Claro,Simples,Reta;Aclive,Sim,Automóvel,"-30,242239","-54,930161",2025,25257.0,0
387366,PR,369.0,447.0,sexta-feira,Plena Noite,Decrescente,Céu Claro,Simples,Reta,Não,NaN,"-24,5543","-52,9553",2023,20055.0,0

# 3 EXPORT

In [14]:
ac_frota.to_csv(os.path.join(data_dir, "tratados/acidentes_frota_21-25.csv"), index=False)
amostra.to_csv(os.path.join(data_dir, "tratados/amostra_21-25.csv"), index=False)